### ISSUE TITLE
The List plugin stopped working with the latest 2.0 version

### ISSUE THREAD

**Issue by eliezerben** [editor-js/list#110]
With the 2.0 version of the list plugin, we are seeing this error:
`Uncaught ReferenceError: List is not defined`

When I use v1.10.0, it works fine.

Code which throws error:
```
<script src="https://cdn.jsdelivr.net/npm/@editorjs/list@latest"></script>
...
...

                list: {
                    class: List,       // This line
                    inlineToolbar: true,
                    shortcut: 'CMD+SHIFT+L'
                },
---
```

**Comment by magarrent** [comment]
Same here!

**Comment by magarrent** [comment]
> since List 2.0 we desided to rename class to `EditorjsList`, so
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/@editorjs/list@latest"></script>
> ...
> 
>                 list: {
>                     class: EditorjsList,
>                     inlineToolbar: true,
>                     shortcut: 'CMD+SHIFT+L'
>                 },
> ```
> 
> would work

Is this documented somewhere?? Didn’t see anything

**Comment by thecliffparis** [comment]
```
<script src="https://cdn.jsdelivr.net/npm/@editorjs/list@latest"></script>
...

                list: {
                    class: EditorjsList,
                    inlineToolbar: true,
                    shortcut: 'CMD+SHIFT+L'
                },
```

With the update, adding a List item is working fine now.
But if we try to convert a text into a list, the list option is not available.

What shall we do to display the option List in the conversion menu ?

**Comment by thecliffparis** [comment]
> ```
> <script src="https://cdn.jsdelivr.net/npm/@editorjs/list@latest"></script>
> ...
> 
>                 list: {
>                     class: EditorjsList,
>                     inlineToolbar: true,
>                     shortcut: 'CMD+SHIFT+L'
>                 },
> ```
> 
> With the update, adding a List item is working fine now. But if we try to convert a text into a list, the list option is not available.
> 
> What shall we do to display the option List in the conversion menu ?

Working fine... Just needed to remove legacy Checklist.
EditorjsList is the only needed for all lists.

**Comment by eliezerben** [comment]
Would be great if the docs were updated. https://github.com/editor-js/list#usage

**Comment by matthewhutchings** [comment]
this has broken a third party script and now I have to try and fix it.

**Comment by neSpecc** [comment]
> is there a cdn for version 1?

https://cdn.jsdelivr.net/npm/@editorjs/list@1
