### ISSUE TITLE
Can't convert other blocks to a list block

### ISSUE THREAD

**Issue by thecliffparis** [editor-js/list#112]
We can't convert block from paragraph to list, title to list... only list items to ordered, unordered, etc.
How to add a block conversion to a list on all block types ?

My current code
```
const inlineToolbarConfig = ['bold', 'italic', 'underline', 'link'];

var editor = EditorJS({
  // ...
  tools: {
    ...
        list: {
            class: EditorjsList, 
            inlineToolbar: inlineToolbarConfig
        }
  //...
});
```

**Comment by e11sy** [comment]
as i can see, paragraph is convertable to list
![image](https://github.com/user-attachments/assets/df981a88-10fa-46c2-aa9b-c6ed10c3a93a)
can you specify the issue?

**Comment by thecliffparis** [comment]
> as i can see, paragraph is convertable to list ![image](https://private-user-images.githubusercontent.com/130844513/387317706-df981a88-10fa-46c2-aa9b-c6ed10c3a93a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5NTExNjQsIm5iZiI6MTczMTk1MDg2NCwicGF0aCI6Ii8xMzA4NDQ1MTMvMzg3MzE3NzA2LWRmOTgxYTg4LTEwZmEtNDZjMi1hYTliLWM2ZWQxMGMzYTkzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQxNzI3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NWIzMzQ4ZmM3YzY3YTgyODIxYmJjZmE1YmY0ZDNlZWVkYjQ1MDAxYWMwNzg5Mjc3ODcxYTdiYzc3N2IzYTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2jxQjcuRdvWdWDuLT5xmQVBSeyvBuJA9ElO2CyxZgEY) can you specify the issue?

![image](https://github.com/user-attachments/assets/2b06c03f-2ff6-4c99-bc8a-1db2c711b901)
In my configuration, there is no List options in "Convert".
There used to be with class List before.

What should I check to make sure it's active ?

**Comment by e11sy** [comment]
can you specify your editorjs version, i will try to reproduce the issue

**Comment by thecliffparis** [comment]
> can you specify your editorjs version? i will try to reproduce the issue

```
<script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/list@latest"></script>

const inlineToolbarConfig = ['bold', 'italic', 'underline', 'link'];

var editor = EditorJS({
  // ...
  tools: {
    ...
        list: {
            class: EditorjsList, 
            inlineToolbar: inlineToolbarConfig
        }
  //...
});
```
tools include Paragraph, Header, EditorjsList, Table, CustomImage, CustomUnderline

**Comment by thecliffparis** [comment]
> > can you specify your editorjs version? i will try to reproduce the issue
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>
> <script src="https://cdn.jsdelivr.net/npm/@editorjs/list@latest"></script>
> 
> const inlineToolbarConfig = ['bold', 'italic', 'underline', 'link'];
> 
> var editor = EditorJS({
>   // ...
>   tools: {
>     ...
>         list: {
>             class: EditorjsList, 
>             inlineToolbar: inlineToolbarConfig
>         }
>   //...
> });
> ```
> 
> tools include Paragraph, Header, EditorjsList, Table, CustomImage, CustomUnderline

I found the problem. I tried to manipulate toolbox with icon and title.
Is there a way to manipulate toolbox from EditorjsList ?

**Comment by thecliffparis** [comment]
working :)
```
list: {
            class: EditorjsList, 
            toolbox: [
                { title: 'unordered custom' },
                { title: 'ordered custom' },
                { title: 'checklist custom' }
            ]
        }
```
