### ISSUE TITLE
v2 has changed the module name from List to EditorjsList?

### ISSUE THREAD

**Issue by hobailey** [editor-js/list#113]
Since the new version of list (v2) that was released this week, our JS code and implementation of Editor JS is suddenly broken 😢 

Here's a stripped down demo of it not working:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
  </head>
  <body>
    <div id="editorjs_content"></div>

    <script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/list@latest"></script>

    <script type="text/javascript">
          new EditorJS({
              holder: "editorjs_content",
              tools: {
                  list: {
                    class: List,
                    inlineToolbar: true,
                    config: {
                      defaultStyle: 'unordered'
                    },
                  },
              }
          });
    </script>
  </body>
</html>

```

On further investigation, it seems that the module/class name (not sure if that's the right terminology?) has changed from `List` to `EditorjsList`, and changing that above fixes the issue. This is a breaking change (and discussed above) but there is no mention of this breaking change nor is this new/different name mentioned in the readme. I'm wondering if the change was perhaps therefore accidental?

**Comment by e11sy** [comment]
change was not accidental, we made it to avoid same naming in future, will update readme with this information very soon

**Comment by hobailey** [comment]
Ok, thanks for the quick reply - that's great to have it confirmed.

Could I suggest adding a clear section in the readme about this breaking change with v2 then so that everyone who is upgrading is aware?

**Comment by e11sy** [comment]
We already working on it, these changes will appear soon
