### ISSUE TITLE
Feature request: Convert group of elements or single element to list

### ISSUE THREAD

**Issue by evanjmg** [editor-js/list#12]
Right now, I can't seem to convert existing content to a list format. First getting a single element to a list is good, but ultimately I should be able to select multiple elements and convert to a list with conversionConfig https://github.com/codex-team/editor.js/blob/next/docs/tools.md#internal-tool-settings

**Comment by evanjmg** [comment]
Implemented it myself - works fine for me. https://github.com/editor-js/nested-list/pull/13

**Comment by e11sy** [comment]
implemented since #13
