### ISSUE TITLE
renderFromHTML duplicates nested lists content

### ISSUE THREAD

**Issue by thecliffparis** [editor-js/list#121]
Hi,

renderFromHTML duplicates lists content in the editor.

Here is an example to reproduce the error.
I hope this helps to fix the bug.

```
<script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>
<script src="https://cdn.jsdelivr.net/npm/@editorjs/list@latest"></script>
...

editor.blocks.renderFromHTML(`<div>  
<ul>
    <li>David 1
      <ul>
        <li>Bulletpoint 1.A</li>
        <li>Bulletpoint 1.B</li>
      </ul>
    </li>
    <li>Erica 2
      <ul>
        <li>Bulletpoint 2.A</li>
        <li>Bulletpoint 2.B</li>
      </ul>
    </li>
  </ul>
</div>`);
```

![image](https://github.com/user-attachments/assets/0ee52c79-e49e-47ef-a553-c430254af4c7)

Should be like this
![image](https://github.com/user-attachments/assets/4f5aeb2e-da6b-4321-8029-5c1700998314)

**Comment by pjurco** [comment]
Is this solved? I have the current version and the problem persists. I tested 2.0.4, 2.0.2 and even 1.10.0. When copying a multi-level list, it copies the content twice. Exactly like in the pictures above.

**Comment by thecliffparis** [comment]
> Is this solved? I have the current version and the problem persists. I tested 2.0.4, 2.0.2 and even 1.10.0. When copying a multi-level list, it copies the content twice. Exactly like in the pictures above.

I confirm. The problem still persists.
I add to do a workaround.
