### ISSUE TITLE
Nested list support

### ISSUE THREAD

**Issue by zwz** [editor-js/list#16]
It is quite common to have nested list in a document. For example, github would convert
```
1. item1
    - test
       1. test1
       2. test2
    - test
1. item2
    This is some text for item2  
```
into

1. item1
    - test
       1. test1
       2. test2
    - test
1. item2
    This is some text for item2  

I really hope that it would be supported in a block-styled editor.

**Comment by bravik** [comment]
That was one of a weak points for quill.js, and also in this editor... Prevents me from migrations from Quill.

**Comment by Froxz** [comment]
Is this in plans at all?

**Comment by tomekszeliga** [comment]
@neSpecc ? any news about it ? :)

**Comment by neSpecc** [comment]
This good feature is waiting for contributors who are ready to implement some stuff.

**Comment by ryanmcdonough** [comment]
Is there a way for us to add a 'bounty' to this to provide some incentive to this issue?

**Comment by khan9920** [comment]
Has anybody figured out how to do this?

**Comment by bravik** [comment]
Only as a hack, but works for me:

Add JS file:
https://gist.github.com/bravik/eaa2a1575965a8e60d8f817b2cde0602

```js
import {breakDown, fixUp} from '../../shared/quill-fix-lists.js';

// On initial load or on external (out of editor) value change
const value = breakDown(this.value);
const contents = this.editor.clipboard.convert(value);
this.editor.setContents(contents); // Set initial editor content

or just (do your own expeirments)
this.editor.root.innerHTML = breakDown(val);


// On editor value change (inside of editor)
const value = fixUp(this.editor.getHtml());
```

In fact I'm replacing quill with TinyMCE in my projects. Quill is dead

**Comment by Froxz** [comment]
@bravik how this helps for editor-js?

**Comment by bravik** [comment]
@Froxz aww.. sorry.. I've mistaken with quilljs

**Comment by evanjmg** [comment]
This new plugin works well :) https://github.com/editor-js/nested-list

**Comment by neSpecc** [comment]
Resolved by making an advanced [Nested List](https://github.com/editor-js/nested-list) tool
