### ISSUE TITLE
Converted List cant create new line

### ISSUE THREAD

**Issue by wtoalabi** [editor-js/list#26]
Great job with this editor!
Falling in love with it every minute.
Kudos to the whole community!!!!
I have a rather thrival question:
When I convert a paragraph to a List, I find that when I press Enter, instead of a new line to showup and the List increment (if Numbered List), it just stays on that  page.
Nothing happens.
No new line is created and the list is not incremented.

I think this is a bug.
Thanks for helping me take a look!

**Comment by tsmith123** [comment]
@wtoalabi Did you ever resolve this issue as I'm facing exactly the same thing.
Pressing return at the end of a list item does not create a new line.

I'm using v2.19.0

**Comment by neSpecc** [comment]
Seems fixed.
