### ISSUE TITLE
Sometime lists doesn't work

### ISSUE THREAD

**Issue by hkmsadek** [editor-js/list#27]
Hi, some time hitting enter make a new list item and sometime it stuck. Most of the time it stuck after adding some contents such image etc. Sometime, when hit enter nothing happens. Any reason why?

**Comment by Phivan** [comment]
Hello,

I have the same issue, but I guess it's because of this :
https://github.com/codex-team/editor.js/issues/746#issuecomment-490426630

Any workaround would be nice.

**Comment by Farrien** [comment]
> Hello,
> 
> I have the same issue, but I guess it's because of this :
> [codex-team/editor.js#746 (comment)](https://github.com/codex-team/editor.js/issues/746#issuecomment-490426630)
> 
> Any workaround would be nice.

8 May 2019 oh god :(

Also met this bug

**Comment by ceesvanegmond** [comment]
Same bug here. The example on the homepage doesn't work either

**Comment by solace** [comment]
Is there a fix for this yet? #48 has been open since last September. Thanks!

**Comment by neSpecc** [comment]
Should be fixed
