### ISSUE TITLE
Any plan to support sub/hierarchy unordered list?

### ISSUE THREAD

**Issue by taurenshaman** [editor-js/list#29]
Scenario:  
Outline. 

reference:
Workflowy, Roam, ...

e.g. 
![image](https://user-images.githubusercontent.com/1308706/77441058-f6b21c80-6e23-11ea-9d36-48dd70864571.png)

**Comment by ItechIndrustries** [comment]
Yes please tell is there any way to add this

**Comment by neSpecc** [comment]
Resolved by making an advanced [Nested List](https://github.com/editor-js/nested-list) tool

**Comment by kanejamison** [comment]
From what I can tell there isn't feature parity or backwards compatibility with the Nested List tool. It would be great if nested functionality was native in the core list plugin here. Maintaining a single strong List plugin where indent/nesting is a toggleable feature feels like the best experience across the EditorJS plugin ecosystem...
