### ISSUE TITLE
Pressing ENTER to get out of list is not working

### ISSUE THREAD

**Issue by pablo-abc** [editor-js/list#30]
Currently pressing enter to get out of the list into a new block is not working.
The current behaviour creates a new block, the last (empty) list element is removed but the caret remains on the list block (although not functioning to write).
If enter is pressed again, a second new block is created and it moves to that one (now having an empty block before).

![bug demo](https://user-images.githubusercontent.com/40573613/78973169-916d5500-7acc-11ea-9490-b707c7ee43b8.gif)

I have tested this in Safari, Chrome and Firefox on MacOS

**Comment by mkeida** [comment]
Same here... any solutions?

**Comment by hata6502** [comment]
https://github.com/codex-team/editor.js/issues/899

**Comment by hata6502** [comment]
https://github.com/codex-team/editor.js/issues/899

**Comment by neSpecc** [comment]
Fixed
