### ISSUE TITLE
Turning paragraph into list item by hitting backspace at the beginning

### ISSUE THREAD

**Issue by alexanderjulmer** [editor-js/list#32]
**Expected behavior**: Hitting backspace at the beginning of a non-empty paragraph that is located behind a list attaches the paragraph's text to the last list item.

```
* This
* is a
* list

|Some paragraph…. <- Cursor at the beginning of the paragraph, hit backspace
```
turns into 
```
* This
* is a 
* listSome paragraph….  <- Paragraph attached to the last list item
```

**Actual behavior**: Hitting backspace moves cursor to the end of the last list item and leaves the paragraph unchanged.

**Reasoning**: Users use this behaviour to turn paragraphs they have written into list items. Similarly, see also #27, #30. Attaching a paragraph the the last list items as described above is standard behaviour of Word, Google Docs and Notion.

**Comment by mooncodee** [comment]
Hello! Do you have any updates of this?
