### ISSUE TITLE
Paste not working because of sanitize

### ISSUE THREAD

**Issue by medzhidov** [editor-js/list#46]
Just add this:
```
static get sanitize() {
        return {
            ol: {},
            ul: {},
            li: {}
        };
    }
```

**Comment by talyguryn** [comment]
cannot reproduce a problem in the main branch. pasting works correctly.

please add more information.

**Comment by medzhidov** [comment]
@talyguryn I use it in "next" branch

**Comment by talyguryn** [comment]
in the next branch I still don't see any problems

![image](https://user-images.githubusercontent.com/15259299/209793276-d2d6e3fb-c325-49c9-9340-c4fa9a636c3a.png)

**Comment by notaloop0000** [comment]
It occurs to my application too. Create an inherited class does not fix, 
```
export class EnhancedNestedListTool extends NestedListTool {
  static get sanitize(){
    return {
      a: {},
      b: {},
      code: {},
      i: {},
    }
  }
}

```

**Comment by e11sy** [comment]
closed as outdated
