### ISSUE TITLE
Output format: Which properties (if any) can be null omitted?

### ISSUE THREAD

**Issue by cmeeren** [editor-js/list#57]
For a valid list block, can any of the `style` or `items` properties under any circumstances (now or in the future) be `null` or omitted, and can any array element in `items` be `null` (or will it always be at least an empty string)? Or are they guaranteed to always be present and non-`null` for this block to be valid?

Context: I'm a back-end .NET developer needing to parse Editor.js documents. The readme lists all of the aforementioned properties but does not explicitly guarantee that they will always be present and non-null. Back-end deserialization/parsing in strongly typed languages would be easier with some guarantees about which properties can and can not be null/omitted. (Ideally, any such guarantees should be added to the readme to ensure they are formalized and kept in the future.)

**Comment by neSpecc** [comment]
Item can be an empty string, but not `null`. Style can't be `null`.

**Comment by cmeeren** [comment]
Thanks a lot!

**Comment by cmeeren** [comment]
Just to be clear: Can `items` itself ever be `null`, or will it always be at least an empty (non-`null`) array?

**Comment by neSpecc** [comment]
> Just to be clear: Can `items` itself ever be `null`, or will it always be at least an empty (non-`null`) array?

yes, it will be an array
