### ISSUE TITLE
Use of formatted content inside list

### ISSUE THREAD

**Issue by pauloamorimbr** [editor-js/list#58]
Hi. I could not find a way to enable or to allow the use of the paragraph like toolbar with html components while in the list items.
Case: My user wants to add links inside list items, but the toolbar for link creation wont popup (or exist, fo that matter) like it does for the paragraph.

**Comment by neSpecc** [comment]
You should specify `inlineToolbar: true` [option](https://editorjs.io/enable-inline-toolbar#enable-inline-toolbar).

**Comment by hamdigaied** [comment]
hello @neSpecc and @pauloamorimbr ,
please how can I set the inlineToolbar: true to enable formatting inside a list element.

`<ReactEditorJS
    onChange={handleSave}
    onInitialize={handleInitialize}
    placeholder="Email body"
    data={editorState}
    defaultValue={editorState}
    tools={{ list: List }}
    inlineToolbar={true}
  />`

Thank you !
