### ISSUE TITLE
How to invoke list manually?

### ISSUE THREAD

**Issue by FractalHQ** [editor-js/list#69]
One feature I like about Notion is that when you type `-` and hit `space`, it will automatically add a list item.

If I wanted to add this feature- what's the best approach?  Can I hook into the class somehow to manually add a list?

**Comment by neSpecc** [comment]
Yes, this is a cool feature that we want to have. It is related to the Editor.js Core. Follow that issue: https://github.com/codex-team/editor.js/issues/709
