### ISSUE TITLE
Caret/Cursor jumps to different list item when using backspace/delete-key

### ISSUE THREAD

**Issue by WolfBearGames** [editor-js/list#74]
I have a nested list of items and click on one of them, setting the cursor to the middle or end of the item. When I hit the backspace or delete key the cursor jumps to one of the other list items instead of deleting the character.

I does not happen every time, but often. Inserting a character by typing seems to work correctly.

I spend several hours trying to figure out why this is happening, but could not find anything.

**Comment by e11sy** [comment]
solved since List 2.0.0
