### ISSUE TITLE
Using shortcut keys fails to make defaultStyle effective

### ISSUE THREAD

**Issue by chq1024** [editor-js/list#81]
`  list : {
        class: NestedList,
        config: {
          defaultStyle: 'ordered',
        },
        inlineToolbar: true,
        shortcut:'CTRL+L'
      }`
When I use the defaultStyle of ordered, and I set the shortcut, but when I add the block using the shortcut, I still get unordered

**Comment by e11sy** [comment]
solved since List 2.0.0
