### ISSUE TITLE
[Question] How to upgrade from List to this Nested List plugin?

### ISSUE THREAD

**Issue by gabbydgab** [editor-js/list#87]
We have already created some documents using the [List](https://github.com/editor-js/list) feature but as our requirements evolved we would like to implement this plugin but when we apply the changes the previous data that we have resulted to "undefined"

**Comment by e11sy** [comment]
We have different data structures for List and Nested-list plugins, we would implement convertor in Nested-list 2.0 version (we are working on it now), so it would be possible to use `Nested-list` with List data format

**Comment by collimarco** [comment]
It would be great if List could be upgraded to NestedList for existing projects, keeping backward compatibility.

This would be useful mainly because List has some annoying bugs and it is [no longer maintained](https://github.com/editor-js/list/issues/90#issuecomment-2270999191)
