### ISSUE TITLE
The typescript type file is missing

### ISSUE THREAD

**Issue by HeKvn** [editor-js/list#88]
Where can I download it, please

**Comment by 1sd15** [comment]
Looks like all EditorJS modules, excluding the main editor, are missing types. 
DefinitelyTyped has provided a typing module for the header module. 
They've yet to provide one for the list module.

**Comment by Sozialarchiv** [comment]
Any news?

**Comment by Sozialarchiv** [comment]
This issue is solved and can be closed.

**Comment by neSpecc** [comment]
Resolved by #97, thanks @Sozialarchiv
