### ISSUE TITLE
Add target="_blank" and rel="noreferrer noopener" attributes to external links

### ISSUE THREAD

**Issue by morvit** [editor-js/list#98]
When adding external links through text, the target="_blank" and rel="noreferrer noopener" attributes are not set, as they are in the paragraph plugin.

**Comment by neSpecc** [comment]
How to reproduce?

**Comment by Sozialarchiv** [comment]
@morvit How do add targets? I think the editorjs core link inline function has not this feature. 

Are you using: https://github.com/trinhtam/editorjs-hyperlink
